### ISSUE TITLE
这不正常呀，都没法进入引导

### ISSUE THREAD

**Issue by quzard** [waiwh91/Acer-SF314-52-Hacintosh-with-oc#2]
![C21B05C1-040D-4D08-9204-7CEAE4134709](https://user-images.githubusercontent.com/30899719/107921551-a5fe6180-6fa9-11eb-9e5e-791978913bf8.png)

**Comment by quzard** [comment]
不知道是什么问题造成的。我用U盘引导的

**Comment by waiwh91** [comment]
我是硬盘引导得=。=
我建议仅仅使用oc这个文件夹，整个efi复制过去可能会有问题罢
可以加qq：1932514482 这里交流有点麻烦
